# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterDialog(object):
    def setupUi(self, AlterDialog):
        AlterDialog.setObjectName("AlterDialog")
        AlterDialog.resize(1228, 745)
        self.gridLayout_4 = QtWidgets.QGridLayout(AlterDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(AlterDialog)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 2, 1, 1)
        self.frame = QtWidgets.QFrame(AlterDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(AlterDialog)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget.setFont(font)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButtonNew = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonNew.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonNew.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonNew.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNew.setIcon(icon)
        self.pushButtonNew.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonNew.setFlat(True)
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.gridLayout_2.addWidget(self.pushButtonNew, 0, 0, 1, 1)
        self.pushButtonDelete = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonDelete.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelete.setIcon(icon1)
        self.pushButtonDelete.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonDelete.setFlat(True)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_2.addWidget(self.pushButtonDelete, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(AlterDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditNickName = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditNickName.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditNickName.setFont(font)
        self.lineEditNickName.setObjectName("lineEditNickName")
        self.gridLayout_3.addWidget(self.lineEditNickName, 2, 1, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 3, 2, 1, 1)
        self.gridLayoutFig = QtWidgets.QGridLayout()
        self.gridLayoutFig.setObjectName("gridLayoutFig")
        self.gridLayout_3.addLayout(self.gridLayoutFig, 6, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditName.setFont(font)
        self.lineEditName.setReadOnly(True)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_3.addWidget(self.lineEditName, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.textEditNote = QtWidgets.QTextEdit(self.frame_3)
        self.textEditNote.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditNote.setFont(font)
        self.textEditNote.setObjectName("textEditNote")
        self.gridLayout_3.addWidget(self.textEditNote, 3, 1, 2, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon2)
        self.pushButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setFlat(True)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_3.addWidget(self.pushButtonSave, 4, 2, 1, 1)
        self.lineEditType = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditType.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditType.setFont(font)
        self.lineEditType.setReadOnly(True)
        self.lineEditType.setObjectName("lineEditType")
        self.gridLayout_3.addWidget(self.lineEditType, 1, 1, 1, 2)
        self.DisplayTip = QtWidgets.QPushButton(self.frame_3)
        self.DisplayTip.setObjectName("DisplayTip")
        self.gridLayout_3.addWidget(self.DisplayTip, 5, 2, 1, 1)
        self.labelTip = QtWidgets.QLabel(self.frame_3)
        self.labelTip.setObjectName("labelTip")
        self.gridLayout_3.addWidget(self.labelTip, 5, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_3, 1, 1, 1, 2)

        self.retranslateUi(AlterDialog)
        QtCore.QMetaObject.connectSlotsByName(AlterDialog)

    def retranslateUi(self, AlterDialog):
        _translate = QtCore.QCoreApplication.translate
        AlterDialog.setWindowTitle(_translate("AlterDialog", "Dialog"))
        self.pushButton.setText(_translate("AlterDialog", "Close"))
        self.label.setText(_translate("AlterDialog", "DB overview"))
        self.label_2.setText(_translate("AlterDialog", "Fields Name"))
        self.pushButtonNew.setText(_translate("AlterDialog", "Add a new field"))
        self.pushButtonDelete.setText(_translate("AlterDialog", "Delete field"))
        self.radioButton.setText(_translate("AlterDialog", "numerical"))
        self.label_6.setText(_translate("AlterDialog", "Field Name:"))
        self.label_5.setText(_translate("AlterDialog", "Note:"))
        self.label_3.setText(_translate("AlterDialog", "Field Type:"))
        self.label_4.setText(_translate("AlterDialog", "Field Nick Name:"))
        self.pushButtonSave.setText(_translate("AlterDialog", "Save"))
        self.DisplayTip.setText(_translate("AlterDialog", "Display anyway"))
        self.labelTip.setText(_translate("AlterDialog", "Current field has more than 30 distint values! Hide figure by default!"))
