# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterDialog(object):
    def setupUi(self, AlterDialog):
        AlterDialog.setObjectName("AlterDialog")
        AlterDialog.resize(659, 809)
        self.gridLayout_4 = QtWidgets.QGridLayout(AlterDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(AlterDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(AlterDialog)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(AlterDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditNickName = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditNickName.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditNickName.setFont(font)
        self.lineEditNickName.setObjectName("lineEditNickName")
        self.gridLayout_3.addWidget(self.lineEditNickName, 1, 0, 1, 1)
        self.lineEditType = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditType.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditType.setFont(font)
        self.lineEditType.setReadOnly(True)
        self.lineEditType.setObjectName("lineEditType")
        self.gridLayout_3.addWidget(self.lineEditType, 3, 0, 1, 2)
        self.textEditNote = QtWidgets.QTextEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditNote.setFont(font)
        self.textEditNote.setObjectName("textEditNote")
        self.gridLayout_3.addWidget(self.textEditNote, 5, 0, 1, 2)
        self.pushButtonSave = QtWidgets.QCommandLinkButton(self.frame_3)
        self.pushButtonSave.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_3.addWidget(self.pushButtonSave, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(AlterDialog)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 2, 1, 1)

        self.retranslateUi(AlterDialog)
        QtCore.QMetaObject.connectSlotsByName(AlterDialog)

    def retranslateUi(self, AlterDialog):
        _translate = QtCore.QCoreApplication.translate
        AlterDialog.setWindowTitle(_translate("AlterDialog", "Dialog"))
        self.label.setText(_translate("AlterDialog", "DB overview"))
        self.label_2.setText(_translate("AlterDialog", "Fields Name"))
        self.label_5.setText(_translate("AlterDialog", "Note:"))
        self.label_3.setText(_translate("AlterDialog", "Field Type:"))
        self.label_4.setText(_translate("AlterDialog", "Field Nick Name:"))
        self.pushButtonSave.setText(_translate("AlterDialog", "Save"))
        self.pushButton.setText(_translate("AlterDialog", "Close"))
