# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barcode_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BarcodeDialog(object):
    def setupUi(self, BarcodeDialog):
        BarcodeDialog.setObjectName("BarcodeDialog")
        BarcodeDialog.resize(750, 417)
        self.gridLayout_4 = QtWidgets.QGridLayout(BarcodeDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(BarcodeDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(BarcodeDialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(BarcodeDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxBarcode = QtWidgets.QComboBox(BarcodeDialog)
        self.comboBoxBarcode.setObjectName("comboBoxBarcode")
        self.gridLayout_4.addWidget(self.comboBoxBarcode, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(BarcodeDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(BarcodeDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditRep = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRep.setObjectName("lineEditRep")
        self.gridLayout_3.addWidget(self.lineEditRep, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEditDel = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditDel.setObjectName("lineEditDel")
        self.gridLayout_3.addWidget(self.lineEditDel, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 4, 0, 1, 3)
        self.pushButtonCancel = QtWidgets.QPushButton(BarcodeDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_4.addWidget(self.pushButtonCancel, 6, 1, 1, 1)
        self.pushButtonConfirm = QtWidgets.QPushButton(BarcodeDialog)
        self.pushButtonConfirm.setDefault(True)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.gridLayout_4.addWidget(self.pushButtonConfirm, 6, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(BarcodeDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.lineEditSplit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditSplit.setEnabled(False)
        self.lineEditSplit.setObjectName("lineEditSplit")
        self.gridLayout_2.addWidget(self.lineEditSplit, 1, 2, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 5, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setEnabled(False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 7, 1, 1)
        self.comboBoxPosition = QtWidgets.QComboBox(self.frame_3)
        self.comboBoxPosition.setObjectName("comboBoxPosition")
        self.comboBoxPosition.addItem("")
        self.comboBoxPosition.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxPosition, 0, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 6, 1, 1)
        self.comboBoxSample = QtWidgets.QComboBox(self.frame_3)
        self.comboBoxSample.setObjectName("comboBoxSample")
        self.gridLayout_2.addWidget(self.comboBoxSample, 0, 2, 1, 4)
        self.gridLayout_4.addWidget(self.frame_3, 5, 0, 1, 3)

        self.retranslateUi(BarcodeDialog)
        QtCore.QMetaObject.connectSlotsByName(BarcodeDialog)

    def retranslateUi(self, BarcodeDialog):
        _translate = QtCore.QCoreApplication.translate
        BarcodeDialog.setWindowTitle(_translate("BarcodeDialog", "Dialog"))
        self.label_2.setText(_translate("BarcodeDialog", "Barcode modifier"))
        self.label.setText(_translate("BarcodeDialog", "Sometimes you might want to modify your barcodes due to different  10X runs may share some same barcodes"))
        self.label_3.setText(_translate("BarcodeDialog", "Step 1: determine the field of your barcodes:"))
        self.label_4.setText(_translate("BarcodeDialog", "Step 2: modify barcodes in batches:"))
        self.label_5.setText(_translate("BarcodeDialog", "Replace"))
        self.label_6.setText(_translate("BarcodeDialog", "by"))
        self.pushButtonCancel.setText(_translate("BarcodeDialog", "Cancel"))
        self.pushButtonConfirm.setText(_translate("BarcodeDialog", "Confirm"))
        self.label_7.setText(_translate("BarcodeDialog", "Add sample information from"))
        self.radioButton.setText(_translate("BarcodeDialog", "extract pattern"))
        self.label_8.setText(_translate("BarcodeDialog", "Split by"))
        self.label_9.setText(_translate("BarcodeDialog", "Pattern is the "))
        self.label_10.setText(_translate("BarcodeDialog", "part"))
        self.comboBoxPosition.setItemText(0, _translate("BarcodeDialog", "Front"))
        self.comboBoxPosition.setItemText(1, _translate("BarcodeDialog", "End"))
        self.label_11.setText(_translate("BarcodeDialog", "to"))
