# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchDialog(object):
    def setupUi(self, BatchDialog):
        BatchDialog.setObjectName("BatchDialog")
        BatchDialog.resize(601, 685)
        self.gridLayout_2 = QtWidgets.QGridLayout(BatchDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonCancel = QtWidgets.QPushButton(BatchDialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 5, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(BatchDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 508))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 441, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayoutChar = QtWidgets.QGridLayout()
        self.gridLayoutChar.setObjectName("gridLayoutChar")
        self.gridLayout_3.addLayout(self.gridLayoutChar, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 4, 0, 1, 4)
        self.label = QtWidgets.QLabel(BatchDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(BatchDialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 3)
        self.gridLayoutFig = QtWidgets.QGridLayout()
        self.gridLayoutFig.setObjectName("gridLayoutFig")
        self.gridLayout_2.addLayout(self.gridLayoutFig, 2, 0, 1, 4)
        self.pushButtonOK = QtWidgets.QPushButton(BatchDialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_2.addWidget(self.pushButtonOK, 5, 3, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(BatchDialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 3, 0, 1, 1)
        self.LineEditCutoff = QtWidgets.QLineEdit(BatchDialog)
        self.LineEditCutoff.setObjectName("LineEditCutoff")
        self.gridLayout_2.addWidget(self.LineEditCutoff, 3, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 2)
        self.DisplayTip = QtWidgets.QPushButton(BatchDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DisplayTip.setFont(font)
        self.DisplayTip.setObjectName("DisplayTip")
        self.gridLayout_2.addWidget(self.DisplayTip, 1, 3, 1, 1)
        self.labelTip = QtWidgets.QLabel(BatchDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelTip.setFont(font)
        self.labelTip.setWordWrap(False)
        self.labelTip.setObjectName("labelTip")
        self.gridLayout_2.addWidget(self.labelTip, 1, 0, 1, 3)

        self.retranslateUi(BatchDialog)
        QtCore.QMetaObject.connectSlotsByName(BatchDialog)

    def retranslateUi(self, BatchDialog):
        _translate = QtCore.QCoreApplication.translate
        BatchDialog.setWindowTitle(_translate("BatchDialog", "Know your data"))
        self.pushButtonCancel.setText(_translate("BatchDialog", "Cancel"))
        self.label.setText(_translate("BatchDialog", "Edit the values of :"))
        self.pushButtonOK.setText(_translate("BatchDialog", "Confirm"))
        self.radioButton.setText(_translate("BatchDialog", "This column is numerical"))
        self.LineEditCutoff.setText(_translate("BatchDialog", "Type cutoff here, seprate by ,  (e.g.  500,600,700)"))
        self.DisplayTip.setText(_translate("BatchDialog", "Display anyway"))
        self.labelTip.setText(_translate("BatchDialog", "Current field has > 30 distint values! Hide figure by default!"))
