# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BeesWarmPlotdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeesWarmPlotDialog(object):
    def setupUi(self, BeesWarmPlotDialog):
        BeesWarmPlotDialog.setObjectName("BeesWarmPlotDialog")
        BeesWarmPlotDialog.resize(961, 748)
        self.gridLayout = QtWidgets.QGridLayout(BeesWarmPlotDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(BeesWarmPlotDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.checkBoxDisplayScatter = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxDisplayScatter.setChecked(True)
        self.checkBoxDisplayScatter.setObjectName("checkBoxDisplayScatter")
        self.gridLayout_2.addWidget(self.checkBoxDisplayScatter, 2, 0, 1, 2)
        self.checkBoxDisplayBar = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxDisplayBar.setChecked(True)
        self.checkBoxDisplayBar.setObjectName("checkBoxDisplayBar")
        self.gridLayout_2.addWidget(self.checkBoxDisplayBar, 3, 0, 1, 2)
        self.lineEditGroup = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditGroup.setObjectName("lineEditGroup")
        self.gridLayout_2.addWidget(self.lineEditGroup, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.radioButtonChecked = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonChecked.setObjectName("radioButtonChecked")
        self.gridLayout_2.addWidget(self.radioButtonChecked, 5, 0, 1, 2)
        self.comboBoxColor = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxColor.setObjectName("comboBoxColor")
        self.gridLayout_2.addWidget(self.comboBoxColor, 4, 1, 1, 1)
        self.lineEditData = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditData.setObjectName("lineEditData")
        self.gridLayout_2.addWidget(self.lineEditData, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.PlotVerticalLayout = QtWidgets.QVBoxLayout()
        self.PlotVerticalLayout.setObjectName("PlotVerticalLayout")
        self.gridLayout.addLayout(self.PlotVerticalLayout, 0, 1, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 380, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButtonDraw = QtWidgets.QPushButton(BeesWarmPlotDialog)
        self.pushButtonDraw.setObjectName("pushButtonDraw")
        self.gridLayout.addWidget(self.pushButtonDraw, 2, 0, 1, 1)

        self.retranslateUi(BeesWarmPlotDialog)
        QtCore.QMetaObject.connectSlotsByName(BeesWarmPlotDialog)

    def retranslateUi(self, BeesWarmPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        BeesWarmPlotDialog.setWindowTitle(_translate("BeesWarmPlotDialog", "Dialog"))
        self.groupBox.setTitle(_translate("BeesWarmPlotDialog", "Features for plots"))
        self.label.setText(_translate("BeesWarmPlotDialog", "Data"))
        self.checkBoxDisplayScatter.setText(_translate("BeesWarmPlotDialog", "Display Scatter"))
        self.checkBoxDisplayBar.setText(_translate("BeesWarmPlotDialog", "Display Bar"))
        self.label_3.setText(_translate("BeesWarmPlotDialog", "Color"))
        self.radioButtonChecked.setText(_translate("BeesWarmPlotDialog", "only plot my checked records"))
        self.label_2.setText(_translate("BeesWarmPlotDialog", "Group"))
        self.pushButtonDraw.setText(_translate("BeesWarmPlotDialog", "Draw"))
