# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CloneOptiondialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CloneOptionDialog(object):
    def setupUi(self, CloneOptionDialog):
        CloneOptionDialog.setObjectName("CloneOptionDialog")
        CloneOptionDialog.resize(425, 434)
        self.gridLayout_2 = QtWidgets.QGridLayout(CloneOptionDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.pushButtonCloneMethod2 = QtWidgets.QPushButton(CloneOptionDialog)
        self.pushButtonCloneMethod2.setMinimumSize(QtCore.QSize(350, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG-Icons/Clone2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCloneMethod2.setIcon(icon)
        self.pushButtonCloneMethod2.setIconSize(QtCore.QSize(200, 130))
        self.pushButtonCloneMethod2.setAutoDefault(False)
        self.pushButtonCloneMethod2.setObjectName("pushButtonCloneMethod2")
        self.gridLayout_2.addWidget(self.pushButtonCloneMethod2, 2, 0, 1, 2)
        self.pushButtonCancel = QtWidgets.QPushButton(CloneOptionDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(CloneOptionDialog)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 2)
        self.pushButtonCloneMethod1 = QtWidgets.QPushButton(CloneOptionDialog)
        self.pushButtonCloneMethod1.setMinimumSize(QtCore.QSize(350, 150))
        self.pushButtonCloneMethod1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonCloneMethod1.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG-Icons/Clone1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCloneMethod1.setIcon(icon1)
        self.pushButtonCloneMethod1.setIconSize(QtCore.QSize(200, 130))
        self.pushButtonCloneMethod1.setAutoDefault(False)
        self.pushButtonCloneMethod1.setObjectName("pushButtonCloneMethod1")
        self.gridLayout_2.addWidget(self.pushButtonCloneMethod1, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 2)

        self.retranslateUi(CloneOptionDialog)
        QtCore.QMetaObject.connectSlotsByName(CloneOptionDialog)

    def retranslateUi(self, CloneOptionDialog):
        _translate = QtCore.QCoreApplication.translate
        CloneOptionDialog.setWindowTitle(_translate("CloneOptionDialog", "Dialog"))
        self.pushButtonCloneMethod2.setText(_translate("CloneOptionDialog", "Change-O\n"
"Clustering"))
        self.pushButtonCancel.setText(_translate("CloneOptionDialog", "Cancel"))
        self.label.setText(_translate("CloneOptionDialog", "Please choose clonal identification method"))
        self.pushButtonCloneMethod1.setText(_translate("CloneOptionDialog", "IgBlast\n"
"Alignment"))
