# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_option_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportOptionDialog(object):
    def setupUi(self, ExportOptionDialog):
        ExportOptionDialog.setObjectName("ExportOptionDialog")
        ExportOptionDialog.resize(504, 698)
        self.gridLayout_2 = QtWidgets.QGridLayout(ExportOptionDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(ExportOptionDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(ExportOptionDialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(ExportOptionDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.pushButtonExport = QtWidgets.QPushButton(ExportOptionDialog)
        self.pushButtonExport.setDefault(True)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout_2.addWidget(self.pushButtonExport, 3, 1, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(ExportOptionDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)

        self.retranslateUi(ExportOptionDialog)
        QtCore.QMetaObject.connectSlotsByName(ExportOptionDialog)

    def retranslateUi(self, ExportOptionDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportOptionDialog.setWindowTitle(_translate("ExportOptionDialog", "Dialog"))
        self.label.setText(_translate("ExportOptionDialog", "Choose the fields you want to export"))
        self.checkBox.setText(_translate("ExportOptionDialog", "Check all"))
        self.pushButtonExport.setText(_translate("ExportOptionDialog", "Export"))
        self.pushButtonCancel.setText(_translate("ExportOptionDialog", "Cancel"))
