# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_option_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportOptionDialog(object):
    def setupUi(self, ExportOptionDialog):
        ExportOptionDialog.setObjectName("ExportOptionDialog")
        ExportOptionDialog.resize(735, 698)
        self.gridLayout_3 = QtWidgets.QGridLayout(ExportOptionDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonRemember = QtWidgets.QPushButton(ExportOptionDialog)
        self.pushButtonRemember.setObjectName("pushButtonRemember")
        self.gridLayout_3.addWidget(self.pushButtonRemember, 2, 2, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(ExportOptionDialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(ExportOptionDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 3, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 3)
        self.pushButtonExport = QtWidgets.QPushButton(ExportOptionDialog)
        self.pushButtonExport.setDefault(True)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout_3.addWidget(self.pushButtonExport, 4, 3, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(ExportOptionDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_3.addWidget(self.pushButtonCancel, 4, 4, 1, 1)
        self.frame = QtWidgets.QFrame(ExportOptionDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 5)
        self.frame_2 = QtWidgets.QFrame(ExportOptionDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        self.pushButtonDelete = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_2.addWidget(self.pushButtonDelete, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)

        self.retranslateUi(ExportOptionDialog)
        QtCore.QMetaObject.connectSlotsByName(ExportOptionDialog)

    def retranslateUi(self, ExportOptionDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportOptionDialog.setWindowTitle(_translate("ExportOptionDialog", "Dialog"))
        self.pushButtonRemember.setText(_translate("ExportOptionDialog", "Remember my selection"))
        self.checkBox.setText(_translate("ExportOptionDialog", "Check all"))
        self.pushButtonExport.setText(_translate("ExportOptionDialog", "Export"))
        self.pushButtonCancel.setText(_translate("ExportOptionDialog", "Cancel"))
        self.label.setText(_translate("ExportOptionDialog", "Choose the fields you want to export"))
        self.pushButtonDelete.setText(_translate("ExportOptionDialog", "Delete this config"))
        self.label_2.setText(_translate("ExportOptionDialog", "Load pre-defined config"))
