# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gibson_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GibsonDialog(object):
    def setupUi(self, GibsonDialog):
        GibsonDialog.setObjectName("GibsonDialog")
        GibsonDialog.resize(1299, 799)
        self.gridLayout_3 = QtWidgets.QGridLayout(GibsonDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(GibsonDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.GibsonLEnd = QtWidgets.QLineEdit(self.groupBox)
        self.GibsonLEnd.setObjectName("GibsonLEnd")
        self.gridLayout.addWidget(self.GibsonLEnd, 1, 3, 1, 1)
        self.GibsonKEnd = QtWidgets.QLineEdit(self.groupBox)
        self.GibsonKEnd.setObjectName("GibsonKEnd")
        self.gridLayout.addWidget(self.GibsonKEnd, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.GibsonStart = QtWidgets.QLineEdit(self.groupBox)
        self.GibsonStart.setObjectName("GibsonStart")
        self.gridLayout.addWidget(self.GibsonStart, 0, 1, 1, 1)
        self.GibsonHEnd = QtWidgets.QLineEdit(self.groupBox)
        self.GibsonHEnd.setObjectName("GibsonHEnd")
        self.gridLayout.addWidget(self.GibsonHEnd, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 0, 4, 2, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 5)
        self.pushButtonCancel = QtWidgets.QPushButton(GibsonDialog)
        self.pushButtonCancel.setDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_3.addWidget(self.pushButtonCancel, 3, 3, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonOK = QtWidgets.QPushButton(GibsonDialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_4.addWidget(self.pushButtonOK, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(GibsonDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.pushButtonUp = QtWidgets.QPushButton(GibsonDialog)
        self.pushButtonUp.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonUp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG-Icons/up_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUp.setIcon(icon)
        self.pushButtonUp.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonUp.setFlat(True)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.horizontalLayout.addWidget(self.pushButtonUp)
        self.pushButtonDown = QtWidgets.QPushButton(GibsonDialog)
        self.pushButtonDown.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonDown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG-Icons/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDown.setIcon(icon1)
        self.pushButtonDown.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonDown.setFlat(True)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.horizontalLayout.addWidget(self.pushButtonDown)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 3, 1, 2)
        self.pushButtonConfirm = QtWidgets.QPushButton(GibsonDialog)
        self.pushButtonConfirm.setDefault(True)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.gridLayout_3.addWidget(self.pushButtonConfirm, 3, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(GibsonDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(1048, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(GibsonDialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)

        self.retranslateUi(GibsonDialog)
        QtCore.QMetaObject.connectSlotsByName(GibsonDialog)

    def retranslateUi(self, GibsonDialog):
        _translate = QtCore.QCoreApplication.translate
        GibsonDialog.setWindowTitle(_translate("GibsonDialog", "Dialog"))
        self.groupBox.setTitle(_translate("GibsonDialog", "Gibson connectors"))
        self.label_4.setText(_translate("GibsonDialog", "Gibson Lambda Downstream"))
        self.label_3.setText(_translate("GibsonDialog", "Gibson Heavy Downstream"))
        self.label.setText(_translate("GibsonDialog", "Gibson Upstream"))
        self.label_2.setText(_translate("GibsonDialog", "Gibson Kappa Downstream"))
        self.pushButtonSave.setText(_translate("GibsonDialog", "Save"))
        self.pushButtonCancel.setText(_translate("GibsonDialog", "Cancel"))
        self.pushButtonOK.setText(_translate("GibsonDialog", "I think this seuqnece is OK"))
        self.label_6.setText(_translate("GibsonDialog", "Row Height"))
        self.pushButtonConfirm.setText(_translate("GibsonDialog", "Confirm"))
        self.label_5.setText(_translate("GibsonDialog", "Preview your selections"))
