# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_data_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportDataDialog(object):
    def setupUi(self, ImportDataDialog):
        ImportDataDialog.setObjectName("ImportDataDialog")
        ImportDataDialog.resize(598, 929)
        self.gridLayout_9 = QtWidgets.QGridLayout(ImportDataDialog)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox = QtWidgets.QGroupBox(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButtonHuman = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonHuman.setChecked(True)
        self.radioButtonHuman.setObjectName("radioButtonHuman")
        self.gridLayout_4.addWidget(self.radioButtonHuman, 0, 0, 1, 1)
        self.radioButtonMouse = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMouse.setObjectName("radioButtonMouse")
        self.gridLayout_4.addWidget(self.radioButtonMouse, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 2, 0, 1, 2)
        self.comboBoxGroup = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxGroup.setObjectName("comboBoxGroup")
        self.gridLayout_9.addWidget(self.comboBoxGroup, 5, 1, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(ImportDataDialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 2000))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBoxFileStruc = QtWidgets.QRadioButton(self.groupBox_5)
        self.checkBoxFileStruc.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBoxFileStruc.setObjectName("checkBoxFileStruc")
        self.gridLayout_6.addWidget(self.checkBoxFileStruc, 0, 2, 1, 1)
        self.rdoChoose = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdoChoose.setMinimumSize(QtCore.QSize(0, 20))
        self.rdoChoose.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdoChoose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdoChoose.setObjectName("rdoChoose")
        self.gridLayout_6.addWidget(self.rdoChoose, 0, 0, 1, 1)
        self.rdoFunction = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdoFunction.setMinimumSize(QtCore.QSize(0, 20))
        self.rdoFunction.setChecked(True)
        self.rdoFunction.setObjectName("rdoFunction")
        self.gridLayout_6.addWidget(self.rdoFunction, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(ImportDataDialog)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(ImportDataDialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txtComment = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtComment.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.txtComment.setObjectName("txtComment")
        self.gridLayout_7.addWidget(self.txtComment, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 7, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(ImportDataDialog)
        self.label_4.setMinimumSize(QtCore.QSize(75, 0))
        self.label_4.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rdoProductive = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoProductive.setObjectName("rdoProductive")
        self.gridLayout_5.addWidget(self.rdoProductive, 0, 0, 1, 1)
        self.rdoVandJ = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoVandJ.setChecked(True)
        self.rdoVandJ.setObjectName("rdoVandJ")
        self.gridLayout_5.addWidget(self.rdoVandJ, 1, 0, 1, 1)
        self.rdoAll = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoAll.setObjectName("rdoAll")
        self.gridLayout_5.addWidget(self.rdoAll, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ImportDataDialog)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(ImportDataDialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonOK = QtWidgets.QPushButton(ImportDataDialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.gridLayout_9.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.comboBoxProject = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxProject.setObjectName("comboBoxProject")
        self.gridLayout_9.addWidget(self.comboBoxProject, 4, 1, 1, 2)
        self.comboBoxSubgroup = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxSubgroup.setObjectName("comboBoxSubgroup")
        self.gridLayout_9.addWidget(self.comboBoxSubgroup, 6, 1, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(ImportDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEditRep2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRep2.setEnabled(False)
        self.lineEditRep2.setObjectName("lineEditRep2")
        self.gridLayout_11.addWidget(self.lineEditRep2, 2, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(self.frame_2)
        self.labelName.setObjectName("labelName")
        self.gridLayout_11.addWidget(self.labelName, 4, 1, 1, 2)
        self.radioButtonChain = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonChain.setChecked(True)
        self.radioButtonChain.setAutoExclusive(False)
        self.radioButtonChain.setObjectName("radioButtonChain")
        self.gridLayout_11.addWidget(self.radioButtonChain, 2, 2, 1, 1)
        self.lineEditRep3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRep3.setEnabled(True)
        self.lineEditRep3.setObjectName("lineEditRep3")
        self.gridLayout_11.addWidget(self.lineEditRep3, 3, 1, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 3, 0, 1, 1)
        self.lineEditRep1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRep1.setObjectName("lineEditRep1")
        self.gridLayout_11.addWidget(self.lineEditRep1, 1, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.Annopath = QtWidgets.QLineEdit(self.frame)
        self.Annopath.setText("")
        self.Annopath.setObjectName("Annopath")
        self.gridLayout.addWidget(self.Annopath, 2, 1, 1, 3)
        self.browse10x = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browse10x.setFont(font)
        self.browse10x.setObjectName("browse10x")
        self.gridLayout.addWidget(self.browse10x, 0, 3, 1, 1)
        self.Seqpath = QtWidgets.QLineEdit(self.frame)
        self.Seqpath.setObjectName("Seqpath")
        self.gridLayout.addWidget(self.Seqpath, 1, 1, 1, 3)
        self.gridLayout_12.addWidget(self.frame, 0, 0, 1, 1)
        self.radioButtonFast1 = QtWidgets.QRadioButton(self.tab)
        self.radioButtonFast1.setChecked(True)
        self.radioButtonFast1.setAutoExclusive(False)
        self.radioButtonFast1.setObjectName("radioButtonFast1")
        self.gridLayout_12.addWidget(self.radioButtonFast1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browseFasta = QtWidgets.QToolButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseFasta.setFont(font)
        self.browseFasta.setObjectName("browseFasta")
        self.gridLayout_2.addWidget(self.browseFasta, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 2)
        self.listWidgetFasta = QtWidgets.QListWidget(self.tab_2)
        self.listWidgetFasta.setObjectName("listWidgetFasta")
        self.gridLayout_2.addWidget(self.listWidgetFasta, 2, 0, 1, 2)
        self.radioButtonFast2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButtonFast2.setChecked(True)
        self.radioButtonFast2.setObjectName("radioButtonFast2")
        self.gridLayout_2.addWidget(self.radioButtonFast2, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browseCSV = QtWidgets.QToolButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseCSV.setFont(font)
        self.browseCSV.setObjectName("browseCSV")
        self.gridLayout_3.addWidget(self.browseCSV, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 2)
        self.listWidgetCSV = QtWidgets.QListWidget(self.tab_3)
        self.listWidgetCSV.setObjectName("listWidgetCSV")
        self.gridLayout_3.addWidget(self.listWidgetCSV, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.browseVDB = QtWidgets.QToolButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseVDB.setFont(font)
        self.browseVDB.setObjectName("browseVDB")
        self.gridLayout_10.addWidget(self.browseVDB, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 2)
        self.listWidgetVDB = QtWidgets.QListWidget(self.tab_5)
        self.listWidgetVDB.setObjectName("listWidgetVDB")
        self.gridLayout_10.addWidget(self.listWidgetVDB, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 0, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 2, 0, 1, 1)
        self.toolButtonIgFasta = QtWidgets.QToolButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonIgFasta.setFont(font)
        self.toolButtonIgFasta.setObjectName("toolButtonIgFasta")
        self.gridLayout_13.addWidget(self.toolButtonIgFasta, 3, 1, 1, 1)
        self.lineEditIgOut = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditIgOut.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditIgOut.setObjectName("lineEditIgOut")
        self.gridLayout_13.addWidget(self.lineEditIgOut, 1, 0, 1, 1)
        self.lineEditIgFasta = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditIgFasta.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditIgFasta.setObjectName("lineEditIgFasta")
        self.gridLayout_13.addWidget(self.lineEditIgFasta, 3, 0, 1, 1)
        self.browseIgBlast = QtWidgets.QToolButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseIgBlast.setFont(font)
        self.browseIgBlast.setObjectName("browseIgBlast")
        self.gridLayout_13.addWidget(self.browseIgBlast, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem1, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.browseIMGT = QtWidgets.QToolButton(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseIMGT.setFont(font)
        self.browseIMGT.setObjectName("browseIMGT")
        self.gridLayout_14.addWidget(self.browseIMGT, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 0, 0, 1, 2)
        self.lineEditIMGT = QtWidgets.QLineEdit(self.tab_6)
        self.lineEditIMGT.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditIMGT.setObjectName("lineEditIMGT")
        self.gridLayout_14.addWidget(self.lineEditIMGT, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 0, 0, 1, 1)
        self.browseSEQ = QtWidgets.QToolButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseSEQ.setFont(font)
        self.browseSEQ.setObjectName("browseSEQ")
        self.gridLayout_15.addWidget(self.browseSEQ, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 1, 0, 1, 2)
        self.listWidgetSEQ = QtWidgets.QListWidget(self.tab_7)
        self.listWidgetSEQ.setObjectName("listWidgetSEQ")
        self.gridLayout_15.addWidget(self.listWidgetSEQ, 2, 0, 1, 2)
        self.radioButtonFast3 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButtonFast3.setChecked(True)
        self.radioButtonFast3.setObjectName("radioButtonFast3")
        self.gridLayout_15.addWidget(self.radioButtonFast3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout_9.addWidget(self.tabWidget, 1, 0, 1, 3)

        self.retranslateUi(ImportDataDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImportDataDialog)

    def retranslateUi(self, ImportDataDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDataDialog.setWindowTitle(_translate("ImportDataDialog", "Import records from files/DBs"))
        self.groupBox.setTitle(_translate("ImportDataDialog", "Species"))
        self.radioButtonHuman.setText(_translate("ImportDataDialog", "Human"))
        self.radioButtonMouse.setText(_translate("ImportDataDialog", "Mouse"))
        self.groupBox_5.setTitle(_translate("ImportDataDialog", "Choose grouping options:"))
        self.checkBoxFileStruc.setToolTip(_translate("ImportDataDialog", "use folder structure to group"))
        self.checkBoxFileStruc.setText(_translate("ImportDataDialog", "Group by file structure"))
        self.rdoChoose.setToolTip(_translate("ImportDataDialog", "Select grouping from choices below"))
        self.rdoChoose.setText(_translate("ImportDataDialog", "Choose:"))
        self.rdoFunction.setToolTip(_translate("ImportDataDialog", "Will group based on heavy/kappa/lambda, Functional, Reading frame"))
        self.rdoFunction.setText(_translate("ImportDataDialog", "Functional grouping"))
        self.label_2.setText(_translate("ImportDataDialog", "Project:"))
        self.groupBox_3.setTitle(_translate("ImportDataDialog", "Global Comments/Notations:"))
        self.label_4.setText(_translate("ImportDataDialog", "Subgroup:"))
        self.label.setText(_translate("ImportDataDialog", "Please select your data input source:"))
        self.groupBox_2.setTitle(_translate("ImportDataDialog", "Options"))
        self.rdoProductive.setText(_translate("ImportDataDialog", "Import productive rearrangments only"))
        self.rdoVandJ.setText(_translate("ImportDataDialog", "Import only sequences with V and J genes"))
        self.rdoAll.setText(_translate("ImportDataDialog", "Import all sequences with any IgBlast hits for V"))
        self.label_3.setText(_translate("ImportDataDialog", "Group:"))
        self.pushButtonCancel.setText(_translate("ImportDataDialog", "Cancel"))
        self.pushButtonOK.setText(_translate("ImportDataDialog", "OK"))
        self.lineEditRep2.setText(_translate("ImportDataDialog", "consensus_"))
        self.labelName.setText(_translate("ImportDataDialog", "clonotype2_H1"))
        self.radioButtonChain.setText(_translate("ImportDataDialog", "ChainType(H,L,K)"))
        self.label_19.setText(_translate("ImportDataDialog", "Your sequence name will be: "))
        self.label_15.setText(_translate("ImportDataDialog", "10X seq name: clonotype2_consensus_1"))
        self.label_14.setText(_translate("ImportDataDialog", "Format sequence Name:"))
        self.label_18.setText(_translate("ImportDataDialog", "3) Add prefix:"))
        self.lineEditRep1.setText(_translate("ImportDataDialog", "clonetype"))
        self.label_16.setText(_translate("ImportDataDialog", "1) Replace \"clonotype\" by"))
        self.label_17.setText(_translate("ImportDataDialog", "2) Replace \"consensus_\" by"))
        self.label_5.setText(_translate("ImportDataDialog", "Click to choose your 10X VDJ output folder path:"))
        self.label_7.setText(_translate("ImportDataDialog", "Annotation file:"))
        self.label_6.setText(_translate("ImportDataDialog", "Sequence file:"))
        self.browse10x.setText(_translate("ImportDataDialog", "Browse"))
        self.radioButtonFast1.setText(_translate("ImportDataDialog", "Fast mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImportDataDialog", "10X VDJ"))
        self.browseFasta.setText(_translate("ImportDataDialog", "Browse"))
        self.label_8.setText(_translate("ImportDataDialog", "Click to choose your Fasta files:"))
        self.label_9.setText(_translate("ImportDataDialog", "Sequences from the following files will be processed and imported:"))
        self.radioButtonFast2.setText(_translate("ImportDataDialog", "Fast mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImportDataDialog", "Fasta file"))
        self.browseCSV.setText(_translate("ImportDataDialog", "Browse"))
        self.label_10.setText(_translate("ImportDataDialog", "Click to choose your CSV files:"))
        self.label_11.setText(_translate("ImportDataDialog", "Records from the following files will be imported: (Make sure they follow VGene format)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ImportDataDialog", "CSV file"))
        self.label_12.setText(_translate("ImportDataDialog", "Click to choose your VGene DB (.vdb) files:"))
        self.browseVDB.setText(_translate("ImportDataDialog", "Browse"))
        self.label_13.setText(_translate("ImportDataDialog", "Records from the following VDBs will be imported: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ImportDataDialog", "VGene DB"))
        self.label_21.setText(_translate("ImportDataDialog", "Choose IgBlast output files (output format 3):"))
        self.label_20.setText(_translate("ImportDataDialog", "Choose corresponding FASTA files:"))
        self.toolButtonIgFasta.setText(_translate("ImportDataDialog", "Browse"))
        self.browseIgBlast.setText(_translate("ImportDataDialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ImportDataDialog", "IgBlast"))
        self.browseIMGT.setText(_translate("ImportDataDialog", "Browse"))
        self.label_23.setText(_translate("ImportDataDialog", "Click to choose IMGT output file:(could be a zip file or folder)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("ImportDataDialog", "IMGT"))
        self.label_24.setText(_translate("ImportDataDialog", "Click to choose folder path for your SEQ files:"))
        self.browseSEQ.setText(_translate("ImportDataDialog", "Browse"))
        self.label_22.setText(_translate("ImportDataDialog", "Sequences from the following files will be processed and imported:"))
        self.radioButtonFast3.setText(_translate("ImportDataDialog", "Fast mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("ImportDataDialog", "Seq files"))
