# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_data_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportDataDialog(object):
    def setupUi(self, ImportDataDialog):
        ImportDataDialog.setObjectName("ImportDataDialog")
        ImportDataDialog.resize(597, 773)
        self.gridLayout_9 = QtWidgets.QGridLayout(ImportDataDialog)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(ImportDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.browse10x = QtWidgets.QToolButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browse10x.setFont(font)
        self.browse10x.setObjectName("browse10x")
        self.gridLayout.addWidget(self.browse10x, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.Seqpath = QtWidgets.QLineEdit(self.tab)
        self.Seqpath.setObjectName("Seqpath")
        self.gridLayout.addWidget(self.Seqpath, 1, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.Annopath = QtWidgets.QLineEdit(self.tab)
        self.Annopath.setText("")
        self.Annopath.setObjectName("Annopath")
        self.gridLayout.addWidget(self.Annopath, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 2)
        self.browseFasta = QtWidgets.QToolButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseFasta.setFont(font)
        self.browseFasta.setObjectName("browseFasta")
        self.gridLayout_2.addWidget(self.browseFasta, 0, 1, 1, 1)
        self.listWidgetFasta = QtWidgets.QListWidget(self.tab_2)
        self.listWidgetFasta.setObjectName("listWidgetFasta")
        self.gridLayout_2.addWidget(self.listWidgetFasta, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browseCSV = QtWidgets.QToolButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseCSV.setFont(font)
        self.browseCSV.setObjectName("browseCSV")
        self.gridLayout_3.addWidget(self.browseCSV, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 2)
        self.listWidgetCSV = QtWidgets.QListWidget(self.tab_3)
        self.listWidgetCSV.setObjectName("listWidgetCSV")
        self.gridLayout_3.addWidget(self.listWidgetCSV, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.browseVDB = QtWidgets.QToolButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseVDB.setFont(font)
        self.browseVDB.setObjectName("browseVDB")
        self.gridLayout_10.addWidget(self.browseVDB, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 2)
        self.listWidgetVDB = QtWidgets.QListWidget(self.tab_5)
        self.listWidgetVDB.setObjectName("listWidgetVDB")
        self.gridLayout_10.addWidget(self.listWidgetVDB, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_9.addWidget(self.tabWidget, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(ImportDataDialog)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(ImportDataDialog)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(ImportDataDialog)
        self.label_4.setMinimumSize(QtCore.QSize(75, 0))
        self.label_4.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(366, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 10, 0, 1, 2)
        self.pushButtonCancel = QtWidgets.QPushButton(ImportDataDialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_9.addWidget(self.pushButtonCancel, 10, 2, 1, 1)
        self.pushButtonOK = QtWidgets.QPushButton(ImportDataDialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_9.addWidget(self.pushButtonOK, 10, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(ImportDataDialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 2000))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rdoChoose = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdoChoose.setMinimumSize(QtCore.QSize(0, 20))
        self.rdoChoose.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rdoChoose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rdoChoose.setObjectName("rdoChoose")
        self.gridLayout_6.addWidget(self.rdoChoose, 0, 0, 1, 1)
        self.rdoFunction = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdoFunction.setMinimumSize(QtCore.QSize(0, 20))
        self.rdoFunction.setChecked(True)
        self.rdoFunction.setObjectName("rdoFunction")
        self.gridLayout_6.addWidget(self.rdoFunction, 0, 1, 1, 1)
        self.checkBoxFileStruc = QtWidgets.QRadioButton(self.groupBox_5)
        self.checkBoxFileStruc.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBoxFileStruc.setObjectName("checkBoxFileStruc")
        self.gridLayout_6.addWidget(self.checkBoxFileStruc, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 4, 0, 1, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rdoProductive = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoProductive.setObjectName("rdoProductive")
        self.gridLayout_5.addWidget(self.rdoProductive, 0, 0, 1, 1)
        self.rdoVandJ = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoVandJ.setChecked(True)
        self.rdoVandJ.setObjectName("rdoVandJ")
        self.gridLayout_5.addWidget(self.rdoVandJ, 1, 0, 1, 1)
        self.rdoAll = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoAll.setObjectName("rdoAll")
        self.gridLayout_5.addWidget(self.rdoAll, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButtonMouse = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMouse.setObjectName("radioButtonMouse")
        self.gridLayout_4.addWidget(self.radioButtonMouse, 0, 1, 1, 1)
        self.radioButtonHuman = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonHuman.setChecked(True)
        self.radioButtonHuman.setObjectName("radioButtonHuman")
        self.gridLayout_4.addWidget(self.radioButtonHuman, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 2, 0, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(ImportDataDialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txtComment = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtComment.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.txtComment.setObjectName("txtComment")
        self.gridLayout_7.addWidget(self.txtComment, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 8, 0, 1, 4)
        self.groupBox_4 = QtWidgets.QGroupBox(ImportDataDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.labelpct = QtWidgets.QLabel(self.groupBox_4)
        self.labelpct.setEnabled(True)
        self.labelpct.setObjectName("labelpct")
        self.gridLayout_8.addWidget(self.labelpct, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(50, 20))
        self.progressBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar.setBaseSize(QtCore.QSize(0, 20))
        self.progressBar.setToolTip("")
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_8.addWidget(self.progressBar, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 9, 0, 1, 4)
        self.comboBoxSubgroup = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxSubgroup.setObjectName("comboBoxSubgroup")
        self.gridLayout_9.addWidget(self.comboBoxSubgroup, 7, 1, 1, 3)
        self.comboBoxGroup = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxGroup.setObjectName("comboBoxGroup")
        self.gridLayout_9.addWidget(self.comboBoxGroup, 6, 1, 1, 3)
        self.comboBoxProject = QtWidgets.QComboBox(ImportDataDialog)
        self.comboBoxProject.setObjectName("comboBoxProject")
        self.gridLayout_9.addWidget(self.comboBoxProject, 5, 1, 1, 3)

        self.retranslateUi(ImportDataDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImportDataDialog)

    def retranslateUi(self, ImportDataDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDataDialog.setWindowTitle(_translate("ImportDataDialog", "Dialog"))
        self.label.setText(_translate("ImportDataDialog", "Please select your data input source:"))
        self.label_5.setText(_translate("ImportDataDialog", "Click to choose your 10X VDJ output folder path:"))
        self.browse10x.setText(_translate("ImportDataDialog", "Browse"))
        self.label_6.setText(_translate("ImportDataDialog", "Sequence file:"))
        self.label_7.setText(_translate("ImportDataDialog", "Annotation file:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImportDataDialog", "10X VDJ"))
        self.label_8.setText(_translate("ImportDataDialog", "Click to choose your Fasta files:"))
        self.label_9.setText(_translate("ImportDataDialog", "Sequences from the following files will be processed and imported:"))
        self.browseFasta.setText(_translate("ImportDataDialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImportDataDialog", "Fasta file"))
        self.browseCSV.setText(_translate("ImportDataDialog", "Browse"))
        self.label_10.setText(_translate("ImportDataDialog", "Click to choose your CSV files:"))
        self.label_11.setText(_translate("ImportDataDialog", "Records from the following files will be imported: (Make sure they follow VGene format)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ImportDataDialog", "CSV file"))
        self.label_12.setText(_translate("ImportDataDialog", "Click to choose your VGene DB (.vdb) files:"))
        self.browseVDB.setText(_translate("ImportDataDialog", "Browse"))
        self.label_13.setText(_translate("ImportDataDialog", "Records from the following VDBs will be imported: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ImportDataDialog", "VGene DB"))
        self.label_2.setText(_translate("ImportDataDialog", "Project:"))
        self.label_3.setText(_translate("ImportDataDialog", "Group:"))
        self.label_4.setText(_translate("ImportDataDialog", "Subgroup:"))
        self.pushButtonCancel.setText(_translate("ImportDataDialog", "Cancel"))
        self.pushButtonOK.setText(_translate("ImportDataDialog", "OK"))
        self.groupBox_5.setTitle(_translate("ImportDataDialog", "Choose grouping options:"))
        self.rdoChoose.setToolTip(_translate("ImportDataDialog", "Select grouping from choices below"))
        self.rdoChoose.setText(_translate("ImportDataDialog", "Choose:"))
        self.rdoFunction.setToolTip(_translate("ImportDataDialog", "Will group based on heavy/kappa/lambda, Functional, Reading frame"))
        self.rdoFunction.setText(_translate("ImportDataDialog", "Functional grouping"))
        self.checkBoxFileStruc.setToolTip(_translate("ImportDataDialog", "use folder structure to group"))
        self.checkBoxFileStruc.setText(_translate("ImportDataDialog", "Group by file structure"))
        self.groupBox_2.setTitle(_translate("ImportDataDialog", "Options"))
        self.rdoProductive.setText(_translate("ImportDataDialog", "Import productive rearrangments only"))
        self.rdoVandJ.setText(_translate("ImportDataDialog", "Import only sequences with V and J genes"))
        self.rdoAll.setText(_translate("ImportDataDialog", "Import all sequences with any IgBlast hits for V"))
        self.groupBox.setTitle(_translate("ImportDataDialog", "Species"))
        self.radioButtonMouse.setText(_translate("ImportDataDialog", "Mouse"))
        self.radioButtonHuman.setText(_translate("ImportDataDialog", "Human"))
        self.groupBox_3.setTitle(_translate("ImportDataDialog", "Global Comments/Notations:"))
        self.groupBox_4.setTitle(_translate("ImportDataDialog", "Loading Progress"))
        self.labelpct.setText(_translate("ImportDataDialog", "Loading progress:"))
