# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatternSearchResultDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatternSearchResultDialog(object):
    def setupUi(self, PatternSearchResultDialog):
        PatternSearchResultDialog.setObjectName("PatternSearchResultDialog")
        PatternSearchResultDialog.resize(643, 577)
        self.gridLayout_2 = QtWidgets.QGridLayout(PatternSearchResultDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(PatternSearchResultDialog)
        self.label_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(453, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 3)
        self.radioButtonCheckAll = QtWidgets.QRadioButton(PatternSearchResultDialog)
        self.radioButtonCheckAll.setObjectName("radioButtonCheckAll")
        self.gridLayout_2.addWidget(self.radioButtonCheckAll, 2, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(PatternSearchResultDialog)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.pushButtonReport = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonReport.setObjectName("pushButtonReport")
        self.verticalLayout.addWidget(self.pushButtonReport)
        self.gridLayout_2.addWidget(self.frame_2, 4, 0, 1, 4)
        self.pushButtonClose = QtWidgets.QPushButton(PatternSearchResultDialog)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_2.addWidget(self.pushButtonClose, 5, 3, 1, 1)
        self.frame = QtWidgets.QFrame(PatternSearchResultDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 4)
        self.lineEdit = QtWidgets.QLineEdit(PatternSearchResultDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.gridLayoutMain = QtWidgets.QGridLayout()
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        self.gridLayout_2.addLayout(self.gridLayoutMain, 3, 0, 1, 4)

        self.retranslateUi(PatternSearchResultDialog)
        QtCore.QMetaObject.connectSlotsByName(PatternSearchResultDialog)

    def retranslateUi(self, PatternSearchResultDialog):
        _translate = QtCore.QCoreApplication.translate
        PatternSearchResultDialog.setWindowTitle(_translate("PatternSearchResultDialog", "Dialog"))
        self.label_2.setText(_translate("PatternSearchResultDialog", "Searched Pattern:"))
        self.radioButtonCheckAll.setText(_translate("PatternSearchResultDialog", "Check all records of current table"))
        self.label_5.setText(_translate("PatternSearchResultDialog", "More options:"))
        self.pushButtonReport.setText(_translate("PatternSearchResultDialog", "Make a protein report with my checked records"))
        self.pushButtonClose.setText(_translate("PatternSearchResultDialog", "Close"))
        self.label.setText(_translate("PatternSearchResultDialog", "Pattern Search Results"))
