# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProteinSimilarResultDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProteinSimilarResultDialog(object):
    def setupUi(self, ProteinSimilarResultDialog):
        ProteinSimilarResultDialog.setObjectName("ProteinSimilarResultDialog")
        ProteinSimilarResultDialog.resize(682, 629)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProteinSimilarResultDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEditWindowSize = QtWidgets.QLineEdit(ProteinSimilarResultDialog)
        self.lineEditWindowSize.setReadOnly(True)
        self.lineEditWindowSize.setObjectName("lineEditWindowSize")
        self.gridLayout_2.addWidget(self.lineEditWindowSize, 2, 3, 1, 1)
        self.gridLayoutMain = QtWidgets.QGridLayout()
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        self.gridLayout_2.addLayout(self.gridLayoutMain, 4, 0, 1, 4)
        self.frame = QtWidgets.QFrame(ProteinSimilarResultDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 4)
        self.lineEditTargetName = QtWidgets.QLineEdit(ProteinSimilarResultDialog)
        self.lineEditTargetName.setReadOnly(True)
        self.lineEditTargetName.setObjectName("lineEditTargetName")
        self.gridLayout_2.addWidget(self.lineEditTargetName, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ProteinSimilarResultDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProteinSimilarResultDialog)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 4)
        self.pushButtonCancel = QtWidgets.QPushButton(ProteinSimilarResultDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(ProteinSimilarResultDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.pushButtonReport = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonReport.setObjectName("pushButtonReport")
        self.verticalLayout.addWidget(self.pushButtonReport)
        self.pushButtonExport = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonExport.setAutoDefault(False)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.verticalLayout.addWidget(self.pushButtonExport)
        self.gridLayout_2.addWidget(self.frame_2, 5, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(ProteinSimilarResultDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.radioButtonCheckAll = QtWidgets.QRadioButton(ProteinSimilarResultDialog)
        self.radioButtonCheckAll.setObjectName("radioButtonCheckAll")
        self.gridLayout_2.addWidget(self.radioButtonCheckAll, 3, 0, 1, 1)

        self.retranslateUi(ProteinSimilarResultDialog)
        QtCore.QMetaObject.connectSlotsByName(ProteinSimilarResultDialog)

    def retranslateUi(self, ProteinSimilarResultDialog):
        _translate = QtCore.QCoreApplication.translate
        ProteinSimilarResultDialog.setWindowTitle(_translate("ProteinSimilarResultDialog", "Identify Similar Proteins"))
        self.label.setText(_translate("ProteinSimilarResultDialog", "Protein similarity matching results"))
        self.label_4.setText(_translate("ProteinSimilarResultDialog", "Window Size:"))
        self.label_2.setText(_translate("ProteinSimilarResultDialog", "* This page is linked to the main UI. When you click one record, the main UI will be automatically switched to it."))
        self.pushButtonCancel.setText(_translate("ProteinSimilarResultDialog", "Close"))
        self.label_5.setText(_translate("ProteinSimilarResultDialog", "More options:"))
        self.pushButtonReport.setText(_translate("ProteinSimilarResultDialog", "Make a protein report with my checked records"))
        self.pushButtonExport.setText(_translate("ProteinSimilarResultDialog", "Export Results"))
        self.label_3.setText(_translate("ProteinSimilarResultDialog", "Target Sequence:"))
        self.radioButtonCheckAll.setText(_translate("ProteinSimilarResultDialog", "Check all records of current table"))
