# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProteinSimilarResultDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProteinSimilarResultDialog(object):
    def setupUi(self, ProteinSimilarResultDialog):
        ProteinSimilarResultDialog.setObjectName("ProteinSimilarResultDialog")
        ProteinSimilarResultDialog.resize(682, 629)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProteinSimilarResultDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutMain = QtWidgets.QGridLayout()
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        self.gridLayout_2.addLayout(self.gridLayoutMain, 2, 0, 1, 4)
        self.frame = QtWidgets.QFrame(ProteinSimilarResultDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 4)
        self.pushButtonExport = QtWidgets.QPushButton(ProteinSimilarResultDialog)
        self.pushButtonExport.setAutoDefault(False)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout_2.addWidget(self.pushButtonExport, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProteinSimilarResultDialog)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 4)
        self.pushButtonReport = QtWidgets.QPushButton(ProteinSimilarResultDialog)
        self.pushButtonReport.setObjectName("pushButtonReport")
        self.gridLayout_2.addWidget(self.pushButtonReport, 3, 0, 1, 2)
        self.pushButtonCancel = QtWidgets.QPushButton(ProteinSimilarResultDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)

        self.retranslateUi(ProteinSimilarResultDialog)
        QtCore.QMetaObject.connectSlotsByName(ProteinSimilarResultDialog)

    def retranslateUi(self, ProteinSimilarResultDialog):
        _translate = QtCore.QCoreApplication.translate
        ProteinSimilarResultDialog.setWindowTitle(_translate("ProteinSimilarResultDialog", "Dialog"))
        self.label.setText(_translate("ProteinSimilarResultDialog", "Protein similarity matching results"))
        self.pushButtonExport.setText(_translate("ProteinSimilarResultDialog", "Export Results"))
        self.label_2.setText(_translate("ProteinSimilarResultDialog", "* This page is linked to the main UI. When you click one record, the main UI will be automatically switched to it."))
        self.pushButtonReport.setText(_translate("ProteinSimilarResultDialog", "Make a protein report with my checked records"))
        self.pushButtonCancel.setText(_translate("ProteinSimilarResultDialog", "Close"))
