# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qchart_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QchartDialog(object):
    def setupUi(self, QchartDialog):
        QchartDialog.setObjectName("QchartDialog")
        QchartDialog.resize(1082, 710)
        self.gridLayout_2 = QtWidgets.QGridLayout(QchartDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(QchartDialog)
        self.label.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxX = QtWidgets.QComboBox(QchartDialog)
        self.comboBoxX.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxX.setObjectName("comboBoxX")
        self.verticalLayout.addWidget(self.comboBoxX)
        self.radioButtonLogX = QtWidgets.QRadioButton(QchartDialog)
        self.radioButtonLogX.setMaximumSize(QtCore.QSize(300, 16777215))
        self.radioButtonLogX.setAutoExclusive(False)
        self.radioButtonLogX.setObjectName("radioButtonLogX")
        self.verticalLayout.addWidget(self.radioButtonLogX)
        self.label_2 = QtWidgets.QLabel(QchartDialog)
        self.label_2.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBoxY = QtWidgets.QComboBox(QchartDialog)
        self.comboBoxY.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxY.setObjectName("comboBoxY")
        self.verticalLayout.addWidget(self.comboBoxY)
        self.radioButtonLogY = QtWidgets.QRadioButton(QchartDialog)
        self.radioButtonLogY.setMaximumSize(QtCore.QSize(300, 16777215))
        self.radioButtonLogY.setAutoExclusive(False)
        self.radioButtonLogY.setObjectName("radioButtonLogY")
        self.verticalLayout.addWidget(self.radioButtonLogY)
        self.line = QtWidgets.QFrame(QchartDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(QchartDialog)
        self.label_3.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBoxGroup = QtWidgets.QComboBox(QchartDialog)
        self.comboBoxGroup.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxGroup.setObjectName("comboBoxGroup")
        self.verticalLayout.addWidget(self.comboBoxGroup)
        self.radioButtonNum = QtWidgets.QRadioButton(QchartDialog)
        self.radioButtonNum.setMaximumSize(QtCore.QSize(280, 16777215))
        self.radioButtonNum.setAutoExclusive(False)
        self.radioButtonNum.setObjectName("radioButtonNum")
        self.verticalLayout.addWidget(self.radioButtonNum)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(QchartDialog)
        self.label_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEditMin = QtWidgets.QLineEdit(QchartDialog)
        self.lineEditMin.setEnabled(False)
        self.lineEditMin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditMin.setObjectName("lineEditMin")
        self.horizontalLayout_2.addWidget(self.lineEditMin)
        self.label_5 = QtWidgets.QLabel(QchartDialog)
        self.label_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEditMax = QtWidgets.QLineEdit(QchartDialog)
        self.lineEditMax.setEnabled(False)
        self.lineEditMax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditMax.setObjectName("lineEditMax")
        self.horizontalLayout_2.addWidget(self.lineEditMax)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(QchartDialog)
        self.label_6.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comboBoxSize = QtWidgets.QComboBox(QchartDialog)
        self.comboBoxSize.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxSize.setObjectName("comboBoxSize")
        self.verticalLayout.addWidget(self.comboBoxSize)
        self.line_3 = QtWidgets.QFrame(QchartDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButtonResetZoom = QtWidgets.QPushButton(QchartDialog)
        self.pushButtonResetZoom.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButtonResetZoom.setAutoDefault(False)
        self.pushButtonResetZoom.setObjectName("pushButtonResetZoom")
        self.verticalLayout.addWidget(self.pushButtonResetZoom)
        self.line_2 = QtWidgets.QFrame(QchartDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.PlotVerticalLayout = QtWidgets.QVBoxLayout()
        self.PlotVerticalLayout.setObjectName("PlotVerticalLayout")
        self.gridLayout_2.addLayout(self.PlotVerticalLayout, 0, 1, 4, 1)
        self.pushButtonDraw = QtWidgets.QPushButton(QchartDialog)
        self.pushButtonDraw.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButtonDraw.setObjectName("pushButtonDraw")
        self.gridLayout_2.addWidget(self.pushButtonDraw, 3, 0, 1, 1)

        self.retranslateUi(QchartDialog)
        QtCore.QMetaObject.connectSlotsByName(QchartDialog)

    def retranslateUi(self, QchartDialog):
        _translate = QtCore.QCoreApplication.translate
        QchartDialog.setWindowTitle(_translate("QchartDialog", "Dialog"))
        self.label.setText(_translate("QchartDialog", "X axis"))
        self.radioButtonLogX.setText(_translate("QchartDialog", " Log X axis"))
        self.label_2.setText(_translate("QchartDialog", "Y axis"))
        self.radioButtonLogY.setText(_translate("QchartDialog", " Log Y axis"))
        self.label_3.setText(_translate("QchartDialog", "Color by: (optional)"))
        self.radioButtonNum.setText(_translate("QchartDialog", "Numerical"))
        self.label_4.setText(_translate("QchartDialog", "Min"))
        self.label_5.setText(_translate("QchartDialog", "Max"))
        self.label_6.setText(_translate("QchartDialog", "Size by: (optional)"))
        self.pushButtonResetZoom.setText(_translate("QchartDialog", "Reset zoom"))
        self.pushButtonDraw.setText(_translate("QchartDialog", "Draw"))

