# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qchart_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QchartDialog(object):
    def setupUi(self, QchartDialog):
        QchartDialog.setObjectName("QchartDialog")
        QchartDialog.resize(882, 656)
        self.verticalLayoutWidget = QtWidgets.QWidget(QchartDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(320, 70, 421, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.PlotVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.PlotVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.PlotVerticalLayout.setObjectName("PlotVerticalLayout")
        self.pushButtonDraw = QtWidgets.QPushButton(QchartDialog)
        self.pushButtonDraw.setGeometry(QtCore.QRect(480, 550, 112, 32))
        self.pushButtonDraw.setObjectName("pushButtonDraw")

        self.retranslateUi(QchartDialog)
        QtCore.QMetaObject.connectSlotsByName(QchartDialog)

    def retranslateUi(self, QchartDialog):
        _translate = QtCore.QCoreApplication.translate
        QchartDialog.setWindowTitle(_translate("QchartDialog", "Dialog"))
        self.pushButtonDraw.setText(_translate("QchartDialog", "Draw"))
