# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatCheck_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatCheckDialog(object):
    def setupUi(self, StatCheckDialog):
        StatCheckDialog.setObjectName("StatCheckDialog")
        StatCheckDialog.resize(759, 748)
        self.gridLayout_2 = QtWidgets.QGridLayout(StatCheckDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(StatCheckDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayoutFig = QtWidgets.QGridLayout()
        self.gridLayoutFig.setObjectName("gridLayoutFig")
        self.gridLayout_2.addLayout(self.gridLayoutFig, 3, 0, 1, 6)
        self.frame = QtWidgets.QFrame(StatCheckDialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.radioButtonAll = QtWidgets.QRadioButton(self.frame)
        self.radioButtonAll.setChecked(True)
        self.radioButtonAll.setObjectName("radioButtonAll")
        self.buttonGroup = QtWidgets.QButtonGroup(StatCheckDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonAll)
        self.gridLayout_4.addWidget(self.radioButtonAll, 0, 1, 1, 1)
        self.radioButtonChecked = QtWidgets.QRadioButton(self.frame)
        self.radioButtonChecked.setObjectName("radioButtonChecked")
        self.buttonGroup.addButton(self.radioButtonChecked)
        self.gridLayout_4.addWidget(self.radioButtonChecked, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 6)
        self.scrollArea = QtWidgets.QScrollArea(StatCheckDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 733, 505))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 441, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayoutChar = QtWidgets.QGridLayout()
        self.gridLayoutChar.setObjectName("gridLayoutChar")
        self.gridLayout_3.addLayout(self.gridLayoutChar, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 5, 0, 1, 6)
        self.comboBox = QtWidgets.QComboBox(StatCheckDialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 5)
        self.radioButton = QtWidgets.QRadioButton(StatCheckDialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 4, 0, 1, 1)
        self.LineEditCutoff = QtWidgets.QLineEdit(StatCheckDialog)
        self.LineEditCutoff.setObjectName("LineEditCutoff")
        self.gridLayout_2.addWidget(self.LineEditCutoff, 4, 1, 1, 5)
        self.pushButtonOK = QtWidgets.QPushButton(StatCheckDialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_2.addWidget(self.pushButtonOK, 6, 5, 1, 1)
        self.DisplayTip = QtWidgets.QPushButton(StatCheckDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DisplayTip.setFont(font)
        self.DisplayTip.setObjectName("DisplayTip")
        self.gridLayout_2.addWidget(self.DisplayTip, 2, 5, 1, 1)
        self.labelTip = QtWidgets.QLabel(StatCheckDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelTip.setFont(font)
        self.labelTip.setWordWrap(False)
        self.labelTip.setObjectName("labelTip")
        self.gridLayout_2.addWidget(self.labelTip, 2, 0, 1, 4)
        self.pushButtonCancel = QtWidgets.QPushButton(StatCheckDialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 6, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 4)

        self.retranslateUi(StatCheckDialog)
        QtCore.QMetaObject.connectSlotsByName(StatCheckDialog)

    def retranslateUi(self, StatCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        StatCheckDialog.setWindowTitle(_translate("StatCheckDialog", "Know your data"))
        self.label.setText(_translate("StatCheckDialog", "Field :"))
        self.label_2.setText(_translate("StatCheckDialog", "Focus on:"))
        self.radioButtonAll.setText(_translate("StatCheckDialog", "All records"))
        self.radioButtonChecked.setText(_translate("StatCheckDialog", "Current checked records"))
        self.radioButton.setText(_translate("StatCheckDialog", "This column is numerical"))
        self.LineEditCutoff.setText(_translate("StatCheckDialog", "Type cutoff here, seprate by ,  (e.g.  500,600,700)"))
        self.pushButtonOK.setText(_translate("StatCheckDialog", "Update Checks"))
        self.DisplayTip.setText(_translate("StatCheckDialog", "Display anyway"))
        self.labelTip.setText(_translate("StatCheckDialog", "Current field has > 30 distint values! Hide figure by default!"))
        self.pushButtonCancel.setText(_translate("StatCheckDialog", "Close"))
