# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samplingdialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SamplingDialog(object):
    def setupUi(self, SamplingDialog):
        SamplingDialog.setObjectName("SamplingDialog")
        SamplingDialog.resize(1150, 777)
        self.gridLayout_4 = QtWidgets.QGridLayout(SamplingDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(SamplingDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEditPopuSize = QtWidgets.QLineEdit(SamplingDialog)
        self.lineEditPopuSize.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditPopuSize.setReadOnly(True)
        self.lineEditPopuSize.setObjectName("lineEditPopuSize")
        self.gridLayout_4.addWidget(self.lineEditPopuSize, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SamplingDialog)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButtonClose = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_4.addWidget(self.pushButtonClose, 4, 4, 1, 1)
        self.pushButtonSampling = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonSampling.setMaximumSize(QtCore.QSize(400, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG-Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSampling.setIcon(icon)
        self.pushButtonSampling.setObjectName("pushButtonSampling")
        self.gridLayout_4.addWidget(self.pushButtonSampling, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(443, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 4, 2, 1, 1)
        self.pushButtonSelect = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.gridLayout_4.addWidget(self.pushButtonSelect, 4, 3, 1, 1)
        self.lineEditMode = QtWidgets.QLineEdit(SamplingDialog)
        self.lineEditMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditMode.setReadOnly(True)
        self.lineEditMode.setObjectName("lineEditMode")
        self.gridLayout_4.addWidget(self.lineEditMode, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(SamplingDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 5)
        self.label_8 = QtWidgets.QLabel(SamplingDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 2, 1, 3)
        self.tableWidgetResult = QtWidgets.QTableWidget(SamplingDialog)
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(0)
        self.tableWidgetResult.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetResult, 2, 2, 2, 3)
        self.toolBox = QtWidgets.QToolBox(SamplingDialog)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.option1 = QtWidgets.QWidget()
        self.option1.setGeometry(QtCore.QRect(0, 0, 316, 482))
        self.option1.setObjectName("option1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.option1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.option1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditSampSize = QtWidgets.QLineEdit(self.option1)
        self.lineEditSampSize.setObjectName("lineEditSampSize")
        self.gridLayout_2.addWidget(self.lineEditSampSize, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG-Icons/mAB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.option1, icon1, "")
        self.option2 = QtWidgets.QWidget()
        self.option2.setObjectName("option2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.option2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.option2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.option2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEditLevel = QtWidgets.QLineEdit(self.option2)
        self.lineEditLevel.setReadOnly(True)
        self.lineEditLevel.setObjectName("lineEditLevel")
        self.gridLayout_3.addWidget(self.lineEditLevel, 2, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.option2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.option2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 2)
        self.checkBoxPro = QtWidgets.QCheckBox(self.option2)
        self.checkBoxPro.setChecked(True)
        self.checkBoxPro.setAutoExclusive(True)
        self.checkBoxPro.setObjectName("checkBoxPro")
        self.buttonGroup = QtWidgets.QButtonGroup(SamplingDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBoxPro)
        self.gridLayout_3.addWidget(self.checkBoxPro, 4, 0, 1, 4)
        self.checkBoxFix = QtWidgets.QCheckBox(self.option2)
        self.checkBoxFix.setAutoExclusive(True)
        self.checkBoxFix.setObjectName("checkBoxFix")
        self.buttonGroup.addButton(self.checkBoxFix)
        self.gridLayout_3.addWidget(self.checkBoxFix, 5, 0, 1, 2)
        self.label_Stratified = QtWidgets.QLabel(self.option2)
        self.label_Stratified.setObjectName("label_Stratified")
        self.gridLayout_3.addWidget(self.label_Stratified, 6, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 296, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 7, 2, 1, 1)
        self.comboBoxGroupField = QtWidgets.QComboBox(self.option2)
        self.comboBoxGroupField.setObjectName("comboBoxGroupField")
        self.gridLayout_3.addWidget(self.comboBoxGroupField, 1, 0, 1, 5)
        self.lineEditGroupSize = QtWidgets.QLineEdit(self.option2)
        self.lineEditGroupSize.setEnabled(True)
        self.lineEditGroupSize.setReadOnly(False)
        self.lineEditGroupSize.setObjectName("lineEditGroupSize")
        self.gridLayout_3.addWidget(self.lineEditGroupSize, 6, 0, 1, 4)
        self.toolBox.addItem(self.option2, icon1, "")
        self.option3 = QtWidgets.QWidget()
        self.option3.setGeometry(QtCore.QRect(0, 0, 316, 482))
        self.option3.setObjectName("option3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.option3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.option3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 2)
        self.lineEditSampleSize = QtWidgets.QLineEdit(self.option3)
        self.lineEditSampleSize.setObjectName("lineEditSampleSize")
        self.gridLayout_5.addWidget(self.lineEditSampleSize, 0, 2, 1, 2)
        self.labelSample = QtWidgets.QLabel(self.option3)
        self.labelSample.setObjectName("labelSample")
        self.gridLayout_5.addWidget(self.labelSample, 0, 4, 1, 1)
        self.radioButtonPrime = QtWidgets.QRadioButton(self.option3)
        self.radioButtonPrime.setChecked(True)
        self.radioButtonPrime.setObjectName("radioButtonPrime")
        self.gridLayout_5.addWidget(self.radioButtonPrime, 1, 0, 1, 3)
        self.comboBoxPrime = QtWidgets.QComboBox(self.option3)
        self.comboBoxPrime.setObjectName("comboBoxPrime")
        self.gridLayout_5.addWidget(self.comboBoxPrime, 2, 0, 1, 5)
        self.label_12 = QtWidgets.QLabel(self.option3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEditLevel2 = QtWidgets.QLineEdit(self.option3)
        self.lineEditLevel2.setReadOnly(True)
        self.lineEditLevel2.setObjectName("lineEditLevel2")
        self.gridLayout_5.addWidget(self.lineEditLevel2, 3, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.option3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 3, 1, 2)
        self.tableWidgetCookie = QtWidgets.QTableWidget(self.option3)
        self.tableWidgetCookie.setObjectName("tableWidgetCookie")
        self.tableWidgetCookie.setColumnCount(0)
        self.tableWidgetCookie.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidgetCookie, 5, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.option3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 5)
        self.toolBox.addItem(self.option3, icon1, "")
        self.gridLayout_4.addWidget(self.toolBox, 3, 0, 1, 2)

        self.retranslateUi(SamplingDialog)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SamplingDialog)

    def retranslateUi(self, SamplingDialog):
        _translate = QtCore.QCoreApplication.translate
        SamplingDialog.setWindowTitle(_translate("SamplingDialog", "Sampling from B cell population"))
        self.label_9.setText(_translate("SamplingDialog", "Mode:"))
        self.label_3.setText(_translate("SamplingDialog", "Population size:"))
        self.pushButtonClose.setText(_translate("SamplingDialog", "Close"))
        self.pushButtonSampling.setText(_translate("SamplingDialog", "Run sampling"))
        self.pushButtonSelect.setText(_translate("SamplingDialog", "Select my sampling results in VGenes"))
        self.label.setText(_translate("SamplingDialog", "Sampling from your dataset"))
        self.label_8.setText(_translate("SamplingDialog", "Sampling results"))
        self.label_2.setText(_translate("SamplingDialog", "Sample size:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.option1), _translate("SamplingDialog", "Random sampling"))
        self.label_4.setText(_translate("SamplingDialog", "Group by:"))
        self.label_10.setText(_translate("SamplingDialog", "There are "))
        self.label_11.setText(_translate("SamplingDialog", "distinct levels in this group"))
        self.label_5.setText(_translate("SamplingDialog", "Group size:"))
        self.checkBoxPro.setToolTip(_translate("SamplingDialog", "This mode will select at least 1 record from each level"))
        self.checkBoxPro.setText(_translate("SamplingDialog", "Proportionable size"))
        self.checkBoxFix.setText(_translate("SamplingDialog", "Fixed size"))
        self.label_Stratified.setText(_translate("SamplingDialog", "Total"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.option2), _translate("SamplingDialog", "Stratified sampling"))
        self.label_7.setText(_translate("SamplingDialog", "Sample size"))
        self.labelSample.setText(_translate("SamplingDialog", "per PF level"))
        self.radioButtonPrime.setText(_translate("SamplingDialog", "Prime factor"))
        self.label_12.setText(_translate("SamplingDialog", "There are "))
        self.label_13.setText(_translate("SamplingDialog", "distinct levels in this factor"))
        self.label_6.setText(_translate("SamplingDialog", "Sampling factor"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.option3), _translate("SamplingDialog", "Representative sampling(Cookie)"))
