# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samplingdialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SamplingDialog(object):
    def setupUi(self, SamplingDialog):
        SamplingDialog.setObjectName("SamplingDialog")
        SamplingDialog.resize(1168, 797)
        self.gridLayout_4 = QtWidgets.QGridLayout(SamplingDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonClose = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_4.addWidget(self.pushButtonClose, 6, 4, 1, 1)
        self.frame = QtWidgets.QFrame(SamplingDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 6, 1, 1, 2)
        self.toolBox = QtWidgets.QToolBox(SamplingDialog)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 400, 503))
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditSampSize = QtWidgets.QLineEdit(self.page)
        self.lineEditSampSize.setObjectName("lineEditSampSize")
        self.gridLayout_2.addWidget(self.lineEditSampSize, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 421, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/mAB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.comboBoxGroupField = QtWidgets.QComboBox(self.page_3)
        self.comboBoxGroupField.setObjectName("comboBoxGroupField")
        self.gridLayout_3.addWidget(self.comboBoxGroupField, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkBoxPro = QtWidgets.QCheckBox(self.page_3)
        self.checkBoxPro.setChecked(True)
        self.checkBoxPro.setAutoExclusive(True)
        self.checkBoxPro.setObjectName("checkBoxPro")
        self.buttonGroup = QtWidgets.QButtonGroup(SamplingDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBoxPro)
        self.gridLayout_3.addWidget(self.checkBoxPro, 3, 0, 1, 2)
        self.checkBoxFix = QtWidgets.QCheckBox(self.page_3)
        self.checkBoxFix.setAutoExclusive(True)
        self.checkBoxFix.setObjectName("checkBoxFix")
        self.buttonGroup.addButton(self.checkBoxFix)
        self.gridLayout_3.addWidget(self.checkBoxFix, 4, 0, 1, 2)
        self.lineEditGroupSize = QtWidgets.QLineEdit(self.page_3)
        self.lineEditGroupSize.setEnabled(False)
        self.lineEditGroupSize.setObjectName("lineEditGroupSize")
        self.gridLayout_3.addWidget(self.lineEditGroupSize, 5, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 315, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 6, 1, 1, 1)
        self.toolBox.addItem(self.page_3, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 400, 503))
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEditSampleSize = QtWidgets.QLineEdit(self.page_2)
        self.lineEditSampleSize.setObjectName("lineEditSampleSize")
        self.gridLayout_5.addWidget(self.lineEditSampleSize, 0, 1, 1, 1)
        self.radioButtonPrime = QtWidgets.QRadioButton(self.page_2)
        self.radioButtonPrime.setChecked(True)
        self.radioButtonPrime.setObjectName("radioButtonPrime")
        self.gridLayout_5.addWidget(self.radioButtonPrime, 1, 0, 1, 2)
        self.comboBoxPrime = QtWidgets.QComboBox(self.page_2)
        self.comboBoxPrime.setObjectName("comboBoxPrime")
        self.gridLayout_5.addWidget(self.comboBoxPrime, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 3, 0, 1, 2)
        self.tableWidgetCookie = QtWidgets.QTableWidget(self.page_2)
        self.tableWidgetCookie.setObjectName("tableWidgetCookie")
        self.tableWidgetCookie.setColumnCount(0)
        self.tableWidgetCookie.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidgetCookie, 4, 0, 1, 2)
        self.toolBox.addItem(self.page_2, icon, "")
        self.gridLayout_4.addWidget(self.toolBox, 5, 0, 1, 1)
        self.pushButtonSampling = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonSampling.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pushButtonSampling.setObjectName("pushButtonSampling")
        self.gridLayout_4.addWidget(self.pushButtonSampling, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SamplingDialog)
        self.label_3.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButtonSelect = QtWidgets.QPushButton(SamplingDialog)
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.gridLayout_4.addWidget(self.pushButtonSelect, 6, 3, 1, 1)
        self.lineEditPopuSize = QtWidgets.QLineEdit(SamplingDialog)
        self.lineEditPopuSize.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEditPopuSize.setReadOnly(True)
        self.lineEditPopuSize.setObjectName("lineEditPopuSize")
        self.gridLayout_4.addWidget(self.lineEditPopuSize, 3, 0, 1, 1)
        self.tableWidgetResult = QtWidgets.QTableWidget(SamplingDialog)
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(0)
        self.tableWidgetResult.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetResult, 3, 1, 3, 4)
        self.label_8 = QtWidgets.QLabel(SamplingDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 1, 1, 4)

        self.retranslateUi(SamplingDialog)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SamplingDialog)

    def retranslateUi(self, SamplingDialog):
        _translate = QtCore.QCoreApplication.translate
        SamplingDialog.setWindowTitle(_translate("SamplingDialog", "Dialog"))
        self.pushButtonClose.setText(_translate("SamplingDialog", "Close"))
        self.label.setText(_translate("SamplingDialog", "Sampling from your dataset"))
        self.label_2.setText(_translate("SamplingDialog", "Sample size:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("SamplingDialog", "Random sampling"))
        self.label_4.setText(_translate("SamplingDialog", "Group field:"))
        self.label_5.setText(_translate("SamplingDialog", "Group size:"))
        self.checkBoxPro.setText(_translate("SamplingDialog", "Proportionable size"))
        self.checkBoxFix.setText(_translate("SamplingDialog", "Fixed size"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("SamplingDialog", "Stratified sampling"))
        self.label_7.setText(_translate("SamplingDialog", "Sample size"))
        self.radioButtonPrime.setText(_translate("SamplingDialog", "Prime factor"))
        self.label_6.setText(_translate("SamplingDialog", "Sampling factor"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("SamplingDialog", "Representative sampling(Cookie)"))
        self.pushButtonSampling.setText(_translate("SamplingDialog", "Run sampling"))
        self.label_3.setText(_translate("SamplingDialog", "Population size:"))
        self.pushButtonSelect.setText(_translate("SamplingDialog", "Select my sampling results in VGenes"))
        self.label_8.setText(_translate("SamplingDialog", "Sampling results"))
