# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VGenesStartUpDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VGenesStartUpDialog(object):
    def setupUi(self, VGenesStartUpDialog):
        VGenesStartUpDialog.setObjectName("VGenesStartUpDialog")
        VGenesStartUpDialog.resize(824, 738)
        VGenesStartUpDialog.setMaximumSize(QtCore.QSize(824, 738))
        self.gridLayout_3 = QtWidgets.QGridLayout(VGenesStartUpDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(VGenesStartUpDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.btnNew = QtWidgets.QPushButton(self.frame)
        self.btnNew.setMinimumSize(QtCore.QSize(260, 45))
        self.btnNew.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnNew.setFont(font)
        self.btnNew.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG-Icons/blank_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon)
        self.btnNew.setIconSize(QtCore.QSize(30, 30))
        self.btnNew.setAutoDefault(False)
        self.btnNew.setFlat(False)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout.addWidget(self.btnNew, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.cboOpen = QtWidgets.QPushButton(self.frame)
        self.cboOpen.setMinimumSize(QtCore.QSize(260, 45))
        self.cboOpen.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cboOpen.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG-Icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cboOpen.setIcon(icon1)
        self.cboOpen.setIconSize(QtCore.QSize(30, 30))
        self.cboOpen.setAutoDefault(False)
        self.cboOpen.setFlat(False)
        self.cboOpen.setObjectName("cboOpen")
        self.gridLayout.addWidget(self.cboOpen, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(VGenesStartUpDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.cboRecent = QtWidgets.QComboBox(self.frame_3)
        self.cboRecent.setMinimumSize(QtCore.QSize(300, 30))
        self.cboRecent.setMaxVisibleItems(15)
        self.cboRecent.setObjectName("cboRecent")
        self.cboRecent.addItem("")
        self.gridLayout_2.addWidget(self.cboRecent, 0, 1, 1, 1)
        self.radioButtonBackDB = QtWidgets.QRadioButton(self.frame_3)
        self.radioButtonBackDB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.radioButtonBackDB.setObjectName("radioButtonBackDB")
        self.gridLayout_2.addWidget(self.radioButtonBackDB, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(VGenesStartUpDialog)
        self.label_3.setMaximumSize(QtCore.QSize(800, 500))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/PNG-Icons/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(VGenesStartUpDialog)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)

        self.retranslateUi(VGenesStartUpDialog)
        QtCore.QMetaObject.connectSlotsByName(VGenesStartUpDialog)

    def retranslateUi(self, VGenesStartUpDialog):
        _translate = QtCore.QCoreApplication.translate
        VGenesStartUpDialog.setWindowTitle(_translate("VGenesStartUpDialog", "VGenes"))
        self.btnNew.setToolTip(_translate("VGenesStartUpDialog", "Start a new project"))
        self.btnNew.setText(_translate("VGenesStartUpDialog", "New VGene DB"))
        self.cboOpen.setToolTip(_translate("VGenesStartUpDialog", "Find a VGenes database to open"))
        self.cboOpen.setText(_translate("VGenesStartUpDialog", "Open VGene DB"))
        self.label.setText(_translate("VGenesStartUpDialog", "Open recent:"))
        self.cboRecent.setToolTip(_translate("VGenesStartUpDialog", "Click file name to open"))
        self.cboRecent.setItemText(0, _translate("VGenesStartUpDialog", "Select a recently opened VGenes database file"))
        self.radioButtonBackDB.setText(_translate("VGenesStartUpDialog", "Backup my DB"))
        self.label_2.setText(_translate("VGenesStartUpDialog", "Choose a VGenes database file:"))
import VgenesResources_rc
