# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VDBMergeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VDBMergeDialog(object):
    def setupUi(self, VDBMergeDialog):
        VDBMergeDialog.setObjectName("VDBMergeDialog")
        VDBMergeDialog.resize(1029, 636)
        self.gridLayout_2 = QtWidgets.QGridLayout(VDBMergeDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(VDBMergeDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(VDBMergeDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 3, 2, 1, 1)
        self.pushButtonConfirm = QtWidgets.QPushButton(VDBMergeDialog)
        self.pushButtonConfirm.setDefault(True)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.gridLayout_2.addWidget(self.pushButtonConfirm, 3, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(VDBMergeDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.labelInfo = QtWidgets.QLabel(VDBMergeDialog)
        self.labelInfo.setObjectName("labelInfo")
        self.gridLayout_2.addWidget(self.labelInfo, 1, 0, 1, 3)

        self.retranslateUi(VDBMergeDialog)
        QtCore.QMetaObject.connectSlotsByName(VDBMergeDialog)

    def retranslateUi(self, VDBMergeDialog):
        _translate = QtCore.QCoreApplication.translate
        VDBMergeDialog.setWindowTitle(_translate("VDBMergeDialog", "Dialog"))
        self.label.setText(_translate("VDBMergeDialog", "New fileds from your VDBs"))
        self.pushButtonCancel.setText(_translate("VDBMergeDialog", "Cancel"))
        self.pushButtonConfirm.setText(_translate("VDBMergeDialog", "Confirm"))
        self.labelInfo.setText(_translate("VDBMergeDialog", "Please check and confirm new fields from your VDBs"))
